platform :osx, "11.0"

install! 'cocoapods', :disable_input_output_paths => true

target 'BlendFace' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  project "BlendFace.xcodeproj"

  # Pods for CompositeTest
  pod "gRPC-Swift", '~> 1.0.0-alpha.20'
  pod "XCGLogger"
  
  # target 'iShowU SwitcherTests' do
  #   # Pods for testing
  #   pod "Quick"
  #   pod "Nimble"
  # end

end


# post_install do |pi|
#   # Update some framework targets 
#   t = pi.pods_project.targets.select { |t| ['Sourcery', 'Sparkle'].include? t.name }
#   t.each do |t|
#     t.build_configurations.each do |bc|
#       bc.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
#     end
#   end
# end



